import os


class RNAStructure:
    # If you're on the HCC Swan cluster, make sure you've run
    #     module load rnastructure
    # because we'll use `Fold`, which comes from that package.
    # You also need to make sure the `DATAPATH` envar is set by
    # running
    #     export DATAPATH= /util/opt/anaconda/deployed-conda-envs/packages/rnastructure/envs/rnastructure-6.1/share/rnastructure/data_tables
    # Also note that this method can take a constraint file
    # generated by either DMS or SHAPE data. It is not required
    # though and as of right now, I'm not going to use it because
    # not every dataset will have reactivity data.

    def __init__(self):
        self.output = ""
        self.path_to_ct_file = ""

    def execute(self, path, fasta_file, output_path):
        path_to_fold = os.path.abspath(path)
        exec_string = f"{path_to_fold} {os.path.abspath(fasta_file)} ./{output_path}"
        self.path_to_ct_file = os.path.abspath(output_path)
        self.output = os.popen(exec_string).read()

    def get_ss_prediction(self):
        ct2db_path_string = "../ViennaRNA/src/Utils/ct2db"
        exec_string = f"{ct2db_path_string} {self.path_to_ct_file}"
        output = os.popen(exec_string).read()
        strings = output.split("\n")
        ss = strings[-2]
        return ss

